export const guruPassMinterAbi = [
  {
    inputs: [
      { internalType: 'address', name: 'tokenContract', type: 'address' },
      { internalType: 'address', name: 'treasuryAddress', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenContract',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'treasuryAddress',
        type: 'address',
      },
    ],
    name: 'Deployed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'Minted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'tokenPrice',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'stageSupply',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'mustBeHolder',
        type: 'bool',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'beneficiaries',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'beneficiariesPercents',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'stageFinishTime',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'whitelist',
        type: 'address',
      },
    ],
    name: 'StageLaunched',
    type: 'event',
  },
  {
    inputs: [],
    name: 'beneficiaries',
    outputs: [{ internalType: 'address payable', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'beneficiariesPercents',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'gameover',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'mustBeHolder',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stageFinishTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenPrice', type: 'uint256' },
      { internalType: 'uint256', name: '_stageSupply', type: 'uint256' },
      { internalType: 'bool', name: '_mustBeHolder', type: 'bool' },
      {
        internalType: 'address payable',
        name: '_beneficiaries',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_beneficiariesPercents',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_stageDurationDays', type: 'uint256' },
      { internalType: 'address', name: '_whitelist', type: 'address' },
    ],
    name: 'stageLaunch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stageSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'token',
    outputs: [
      { internalType: 'contract GuruPassToken', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tokenPrice',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasury',
    outputs: [{ internalType: 'address payable', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'whitelist',
    outputs: [
      { internalType: 'contract GuruPassWhitelist', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
];
